Pr#10 Preconditions
wolox-training/ldpl-java pull request #10
Opened 2019-09-12 00:19 UTC by leonplondon

# Summary
Added Guava, Preconditions library.
Implemented preconditions on User & Book models (on setters).

# Trello Card
https://trello.com/c/Pc80g0hp/29-agregar-validación-de-precondiciones-a-los-setters

2019-09-16 18:29 UTC, rabinovichm requested changes

2019-09-16 18:29 UTC, rabinovichm commented on src/main/java/wolox/training/models/Book.java
> +        Preconditions.checkNotNull(genre, "Genre can't be null");
Genre can be null :smile: [book model card](https://trello.com/c/F1uZqeMs/14-crear-modelo-de-book)

2019-09-16 18:29 UTC, rabinovichm commented on src/main/java/wolox/training/models/Book.java
> +            .checkArgument(year != null && year.length() == 4 && Integer.parseInt(year) > 0, "I");
Check this error message :yum:

2019-09-16 18:29 UTC, rabinovichm commented on src/main/java/wolox/training/models/User.java
> +        Preconditions.checkNotNull(username, "Username can't be null --->");
What's the "_**--->**_" for?

2019-09-25 15:20 UTC, rabinovichm submitted a review, later dismissed

2019-09-25 17:36 UTC, IgnOliveto submitted a review, later dismissed

2019-10-01 22:33 UTC, IgnOliveto approved these changes

2019-10-04 15:53 UTC, rabinovichm approved these changes

2019-10-04 16:18 UTC, merged