User Model.
wolox-training/ldpl-java pull request #6
Opened 2019-09-10 20:31 UTC by leonplondon

# Summary
Added User Model.
Added Many-To-Many relationship between User & Book.
Added BookAlreadyOwned exception to custom exceptions.

# Trello Card
https://trello.com/c/0q73MoYb/19-crear-modelo-de-user

#Notes
PR pointing to `pr#5-books-crud` because all previous PRs wil be merged soon.

2019-09-11 13:28 UTC, rabinovichm requested changes

2019-09-11 13:28 UTC, rabinovichm commented on src/main/java/wolox/training/models/User.java
> +    private Book myBook;
Why does an user contains one book separated from the books' list? :thinking:

2019-09-11 13:28 UTC, rabinovichm commented on src/main/java/wolox/training/models/Book.java
> +    private List<User> users;
Does the book actually needs to contain the users that are holding it? (it's a real question to know what you think)

2019-09-11 20:05 UTC, leonplondon commented on src/main/java/wolox/training/models/User.java
> +    private Book myBook;
My Bad, was a local test.

2019-09-11 20:06 UTC, leonplondon commented on src/main/java/wolox/training/models/Book.java
> +    private List<User> users;
I think maybe in the future we can use this to get a bidirectional reading between entities.

2019-09-11 20:07 UTC, leonplondon commented on src/main/java/wolox/training/models/Book.java
> +    private List<User> users;
I can remove it, must I?

2019-09-12 04:09 UTC, IgnOliveto commented on src/main/java/wolox/training/models/User.java
> +    @ManyToMany(cascade = CascadeType.ALL)
The CascadeType.ALL argument will remove books if you remove users from the data base. More info [here](https://howtodoinjava.com/hibernate/hibernate-jpa-cascade-types/)

2019-09-12 04:09 UTC, IgnOliveto commented on src/main/java/wolox/training/models/Book.java
> +    private List<User> users;
Bidirectional mapping is ok, no need to remove it.

2019-09-13 03:06 UTC, IgnOliveto commented on src/main/java/wolox/training/models/User.java
> +    @ManyToMany(cascade = {CascadeType.MERGE, CascadeType.PERSIST, CascadeType.DETACH})
In this case the only type of cascade that we need is MERGE, all the other could cause persistence behaviour that we dont want.

2019-09-16 16:34 UTC, rabinovichm commented on src/main/java/wolox/training/models/Book.java
> +    private List<User> users;
Wouldn't it break the [KISS principle](https://en.wikipedia.org/wiki/KISS_principle) by adding a relation that is not needed? I mean, right now it is not necessary to get the users that contain a particular book.

2019-09-16 18:36 UTC, IgnOliveto commented on src/main/java/wolox/training/models/Book.java
> +    private List<User> users;
Yes, we  can avoid it but  i dont see much gain avoiding bidirectional mapping, look at this [example](https://www.baeldung.com/hibernate-many-to-many)

2019-09-23 19:36 UTC, IgnOliveto commented
Good Job!

2019-09-23 19:37 UTC, IgnOliveto approved these changes

2019-09-25 15:17 UTC, rabinovichm approved these changes

2019-09-25 16:24 UTC, merged